#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

CONST="-X main.DNSVersion=${VERSION} -X main.DNSDate='${BUILDDATE}'"

mkdir -p bin
CGO_ENABLED=0 go build -ldflags "$CONST -linkshared -extldflags -static -s -w" -o bin/rdns-server
